"""Tests for post-install engine initialization.

Why these tests exist
---------------------
Installing an engine binary is only half of making it usable: the writable
``.uci`` profile config is generated by launching the engine once and reading the
UCI options it advertises. That second half was performed at two call sites
(``EngineManager.install_engine`` for catalog engines, ``_seed_uci_after_install``
for custom upload/URL installs), each with its own copy of a try/except that
logged the failure and moved on. An engine could therefore finish installing,
fail to initialize, and present itself as "Installed" with no profiles and no
explanation anywhere the user could see.

``engine_bootstrap.initialize_profiles`` is the single implementation of that
step. These tests pin the contract both call sites depend on: it never raises
(the binary is already installed, so a failed probe must not undo the install),
it reports success as a bool, and the reason for a failure is recorded durably
rather than only logged.
"""

import pytest

from universalchess.services import engine_bootstrap
from universalchess.services.engine_failure_record import (
    PHASE_INITIALIZE,
    EngineFailureStore,
)

ENGINE = "ct800"


@pytest.fixture
def store(tmp_path):
    """An isolated failure store so tests never touch the real CONFIG_DIR file."""
    return EngineFailureStore(path=tmp_path / "failures.json")


@pytest.fixture(autouse=True)
def events(monkeypatch):
    """Capture event-log writes instead of appending to the real events file.

    ``log_event`` is the boundary to /var/lib/universalchess/logs/events.jsonl,
    which is neither writable nor isolated in tests. The captured kwargs let the
    assertions check category and level, which is what the Settings viewer
    renders from.
    """
    captured = []
    monkeypatch.setattr(
        engine_bootstrap, "log_event",
        lambda category, message, **kwargs: captured.append(
            {"category": category, "message": message, **kwargs}
        ),
    )
    return captured


def test_returns_true_and_records_nothing_when_seeding_succeeds(monkeypatch, store, tmp_path):
    """A successful seed reports True and leaves no failure record.

    Why this test exists: the healthy path is the one every engine takes, and a
    stray record written here would put a warning badge on every working engine.

    How a regression manifests: get() returns a record for an engine that
    initialized cleanly, so the card contradicts itself in the opposite
    direction from the bug being fixed.
    """
    config = tmp_path / f"{ENGINE}.uci"
    monkeypatch.setattr(
        engine_bootstrap.uci_schema, "seed_config",
        lambda name, **kwargs: str(config),
    )

    assert engine_bootstrap.initialize_profiles(ENGINE, store=store) is True
    assert store.get(ENGINE) is None


def test_clears_a_stale_failure_after_a_successful_reinstall(monkeypatch, store, tmp_path):
    """Seeding successfully retracts the previous failure for that engine.

    Why this test exists: the expected repair for a failed initialize is to
    reinstall. If the record outlived the fix, the user would repair the engine
    and still be told it is broken, which trains them to ignore the warning.

    How a regression manifests: the record survives and the card keeps showing
    the old reason for an engine that now works.
    """
    store.record_failure(ENGINE, phase=PHASE_INITIALIZE, reason_code="incompatible_binary")
    config = tmp_path / f"{ENGINE}.uci"
    monkeypatch.setattr(
        engine_bootstrap.uci_schema, "seed_config",
        lambda name, **kwargs: str(config),
    )

    assert engine_bootstrap.initialize_profiles(ENGINE, store=store) is True
    assert store.get(ENGINE) is None


def test_records_the_probe_reason_and_reports_false(monkeypatch, store):
    """A probe failure is recorded under the initialize phase with its reason.

    Why this test exists: this is the CT800 report -- the binary installs, the
    probe fails, and until now the only trace was a log warning on a board the
    maintainer cannot reach. The reason code carried by EngineProbeError is what
    makes the failure legible in a screenshot.

    How a regression manifests: no record is stored (the card shows a plain
    "Installed" badge again), or the reason is dropped and the UI can only say
    that something unspecified went wrong.
    """
    def failing_seed(name, **kwargs):
        raise engine_bootstrap.uci_schema.EngineProbeError(
            "could not launch", reason_code="incompatible_binary", detail="OSError ENOEXEC"
        )

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", failing_seed)

    assert engine_bootstrap.initialize_profiles(ENGINE, store=store) is False
    failure = store.get(ENGINE)
    assert failure is not None
    assert (failure.phase, failure.reason_code) == (PHASE_INITIALIZE, "incompatible_binary")
    assert failure.detail == "OSError ENOEXEC"


def test_records_a_generic_reason_when_the_probe_error_carries_none(monkeypatch, store):
    """A probe error without a reason still produces a usable record.

    Why this test exists: not every EngineProbeError originates from a launch
    (an invalid engine name raises one before anything is spawned). Those must
    still record something the UI can render, or the card would show a failure
    note with a missing translation key.

    How a regression manifests: reason_code is None, the failure store rejects
    it, and the resulting ValueError escapes a code path whose whole contract is
    that it never raises.
    """
    def failing_seed(name, **kwargs):
        raise engine_bootstrap.uci_schema.EngineProbeError("invalid engine name")

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", failing_seed)

    assert engine_bootstrap.initialize_profiles(ENGINE, store=store) is False
    failure = store.get(ENGINE)
    assert failure is not None
    assert failure.reason_code == "launch_failed"


def test_never_raises_when_seeding_blows_up_unexpectedly(monkeypatch, store):
    """An unexpected exception is contained, not propagated to the installer.

    Why this test exists: this runs at the tail of a successful install. Letting
    an exception out would mark a completed install as failed and offer the user
    a reinstall that cannot help -- the binary is already on disk.

    How a regression manifests: OSError propagates and the install endpoint
    reports "Installation failed" for an engine that installed correctly.
    """
    def exploding_seed(name, **kwargs):
        raise OSError("disk full")

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", exploding_seed)

    assert engine_bootstrap.initialize_profiles(ENGINE, store=store) is False
    failure = store.get(ENGINE)
    assert failure is not None
    assert failure.phase == PHASE_INITIALIZE


def test_writes_an_error_event_naming_the_engine_and_the_reason(monkeypatch, store, events):
    """A failed initialize appends an error to the system event log.

    Why this test exists: the engine card shows only the current failure, and it
    is dismissible. The event log is the durable, timestamped trail that survives
    dismissal and a later successful reinstall -- it is where "this engine has
    failed to start after every install for a week" becomes visible. It also puts
    the engine failure next to the install it followed, in one place a user can
    screenshot.

    How a regression manifests: nothing is appended, and once the card notice is
    dismissed there is no record of the failure anywhere the user can reach.
    """
    def failing_seed(name, **kwargs):
        raise engine_bootstrap.uci_schema.EngineProbeError(
            "could not launch", reason_code="incompatible_binary", detail="OSError ENOEXEC"
        )

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", failing_seed)

    engine_bootstrap.initialize_profiles(ENGINE, display_name="CT800", store=store)

    assert len(events) == 1
    event = events[0]
    assert event["category"] == "engine_init"
    assert event["level"] == "error"
    assert "CT800" in event["message"]
    assert "incompatible_binary" in event["message"]
    assert "OSError ENOEXEC" in event["message"]


def test_writes_no_event_when_initialization_succeeds(monkeypatch, store, events, tmp_path):
    """The healthy path stays out of the event log.

    Why this test exists: the install itself already logs one event per attempt.
    A second "initialized fine" entry for every engine would double the log's
    volume with no information and bury the failures it exists to make visible.

    How a regression manifests: the event log fills with routine entries and the
    error that matters scrolls out of the 200-entry view.
    """
    config = tmp_path / f"{ENGINE}.uci"
    monkeypatch.setattr(
        engine_bootstrap.uci_schema, "seed_config",
        lambda name, **kwargs: str(config),
    )

    engine_bootstrap.initialize_profiles(ENGINE, store=store)

    assert events == []


def test_falls_back_to_the_engine_id_when_no_display_name_is_given(monkeypatch, store, events):
    """Without a display name the event and record still identify the engine.

    Why this test exists: display names live in the engine catalog, which this
    service deliberately does not import (the catalog already depends on it).
    Callers pass the name when they have one; the fallback must not produce an
    entry that names no engine at all.

    How a regression manifests: the event message reads "None did not start" and
    the log entry is useless.
    """
    def failing_seed(name, **kwargs):
        raise engine_bootstrap.uci_schema.EngineProbeError("could not launch")

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", failing_seed)

    engine_bootstrap.initialize_profiles(ENGINE, store=store)

    assert ENGINE in events[0]["message"]


def test_an_unwritable_failure_store_still_leaves_an_event(monkeypatch, tmp_path, events):
    """A store that cannot be written degrades to the event log, silently.

    Why this test exists: recording exists to report a problem and must never be
    able to create one. If persisting raised, an unwritable config dir would turn
    a completed install into a reported failure -- untrue, and the exact inverse
    of what this code is for. The event log entry must still be written so the
    reason is not lost entirely.

    How a regression manifests: PermissionError propagates out of a function
    whose contract is that it never raises, failing the install that produced it.
    """
    from universalchess.services.engine_failure_record import EngineFailureStore

    unwritable = EngineFailureStore(path=tmp_path / "missing" / "failures.json")
    monkeypatch.setattr(
        unwritable, "record_failure",
        lambda *args, **kwargs: (_ for _ in ()).throw(PermissionError("read-only")),
    )

    def failing_seed(name, **kwargs):
        raise engine_bootstrap.uci_schema.EngineProbeError(
            "could not launch", reason_code="incompatible_binary"
        )

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", failing_seed)

    assert engine_bootstrap.initialize_profiles(ENGINE, store=unwritable) is False
    assert len(events) == 1
    assert events[0]["level"] == "error"


def test_forwards_the_config_path_override(monkeypatch, store, tmp_path):
    """An explicit config path reaches seed_config unchanged.

    Why this test exists: the custom upload/URL install path resolves the .uci
    location itself and passes it in. Dropping the argument would seed a custom
    engine's profiles at the wrong path, so the editor would find nothing.

    How a regression manifests: seed_config receives config_path=None and the
    recorded argument below is the default rather than the override.
    """
    seen = {}
    override = str(tmp_path / "custom.uci")

    def recording_seed(name, **kwargs):
        seen.update(kwargs)
        return kwargs.get("config_path") or "/unused"

    monkeypatch.setattr(engine_bootstrap.uci_schema, "seed_config", recording_seed)

    assert engine_bootstrap.initialize_profiles(ENGINE, config_path=override, store=store) is True
    assert seen["config_path"] == override
