"""Tests for the login-time DNS diagnostic installed on the card.

In rpi-usb-gadget's client mode the board takes its nameserver by DHCP from the
host on the other end of the USB cable. A host that advertises itself as a DNS
server without actually running one produces a uniquely unhelpful failure: every
route works, `ping 8.8.8.8` succeeds, and every lookup dies with "Temporary
failure in name resolution" — a message that names nothing and blames nothing.
Users cannot diagnose that, and apt fails until they do.

The script under test turns that mute failure into an explanation at login. It
deliberately configures nothing: an earlier design set `ipv4.dns` on the profile
instead, which was abandoned once testing showed NetworkManager puts
connection-configured servers *ahead* of the DHCP-supplied one, making every
board send all lookups to a public resolver permanently.

The shipped script is executed against fake `getent` and `ip` so the behaviour
cannot drift from the file that lands on the card.
"""

import os
import shutil
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "motd-dns-check.sh"

# A nameserver address that is not any public resolver, so a test asserting the
# script echoes the configured server cannot pass by coincidence.
HOST_NAMESERVER = "192.168.2.1"

# Resolvers the script must never tell the user to configure. The whole point of
# this approach over setting ipv4.dns is that it introduces no DNS leak.
PUBLIC_RESOLVERS = ("1.1.1.1", "8.8.8.8", "9.9.9.9")

DEFAULT_ROUTE = "default via 192.168.2.1 dev usb0 proto dhcp src 192.168.2.3 metric 100"

_FAKE_GETENT = """#!/bin/sh
exit ${UC_TEST_RESOLVES:-0}
"""

_FAKE_IP = """#!/bin/sh
[ -n "$UC_TEST_DEFAULT_ROUTE" ] && echo "$UC_TEST_DEFAULT_ROUTE"
exit 0
"""

# macOS has no coreutils `timeout`, so the bounded path would never be exercised
# on a developer machine without this. It simply drops the duration argument and
# runs the rest.
_FAKE_TIMEOUT = """#!/bin/sh
shift
exec "$@"
"""


def _write_tool(bindir: Path, name: str, body: str) -> None:
    path = bindir / name
    path.write_text(body)
    path.chmod(0o755)


@pytest.fixture
def run_check(tmp_path):
    """Run the shipped script against a PATH containing only known tools.

    PATH is replaced rather than prepended. Prepending would let the host's real
    tools satisfy a lookup the test means to control -- and specifically would
    make `with_timeout=False` untestable on Linux, where a real `timeout` exists
    and would be found regardless. `awk` is symlinked in because the script
    genuinely needs it and there is nothing to fake about it.
    """
    assert SCRIPT.exists(), f"script missing: {SCRIPT}"
    bindir = tmp_path / "bin"
    bindir.mkdir()
    _write_tool(bindir, "getent", _FAKE_GETENT)
    _write_tool(bindir, "ip", _FAKE_IP)

    real_awk = shutil.which("awk")
    assert real_awk, "awk is required to run this script"
    (bindir / "awk").symlink_to(real_awk)

    def run(
        *,
        resolves: bool,
        resolv_conf: str,
        default_route: str = DEFAULT_ROUTE,
        with_timeout: bool = True,
    ) -> str:
        timeout_path = bindir / "timeout"
        if with_timeout:
            _write_tool(bindir, "timeout", _FAKE_TIMEOUT)
        elif timeout_path.exists():
            timeout_path.unlink()

        conf = tmp_path / "resolv.conf"
        conf.write_text(resolv_conf)
        env = dict(os.environ)
        env["PATH"] = str(bindir)
        env["UC_RESOLV_CONF"] = str(conf)
        env["UC_TEST_RESOLVES"] = "0" if resolves else "2"
        env["UC_TEST_DEFAULT_ROUTE"] = default_route
        proc = subprocess.run(  # noqa: S603 - runs the shipped script itself
            ["/bin/sh", str(SCRIPT)],
            env=env,
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        assert proc.returncode == 0, proc.stderr
        return proc.stdout

    return run


WORKING_RESOLV = f"# Generated by NetworkManager\nnameserver {HOST_NAMESERVER}\n"


class TestDnsCheckMotd:
    def test_says_nothing_when_resolution_works(self, run_check):
        """A healthy board must produce no output at all.

        Why this test exists: this script runs on every login. A banner that
        appears when nothing is wrong trains users to ignore it, so the one time
        it matters they will not read it.

        How the regression manifests: any output on a board whose DNS resolves.
        """
        assert run_check(resolves=True, resolv_conf=WORKING_RESOLV) == ""

    def test_explains_the_failure_and_names_the_server(self, run_check):
        """A broken forwarder must be reported, naming the actual server.

        Why this test exists: "Temporary failure in name resolution" identifies
        nothing. The value of this script is entirely in saying *which* server
        is not answering and *where* it came from, so the user knows to look at
        the host rather than the board.

        How the regression manifests: the warning appears but omits the
        nameserver, leaving the user no better off than the kernel message.
        """
        out = run_check(resolves=False, resolv_conf=WORKING_RESOLV)

        assert HOST_NAMESERVER in out
        assert "DHCP" in out
        assert "apt" in out

    def test_reads_the_nameserver_from_resolv_conf_rather_than_assuming(self, run_check):
        """The reported address must come from the file, not a baked-in guess.

        Why this test exists: the host's subnet differs per platform — macOS
        Internet Sharing uses 192.168.2.1, Windows ICS uses 192.168.137.1.
        Printing a hardcoded address would send users chasing a server that is
        not theirs.

        How the regression manifests: the output names 192.168.2.1 when
        resolv.conf says something else.
        """
        out = run_check(
            resolves=False,
            resolv_conf="nameserver 192.168.137.1\n",
        )

        assert "192.168.137.1" in out
        assert HOST_NAMESERVER not in out

    def test_never_recommends_configuring_a_public_resolver(self, run_check):
        """The advice must not push users into a permanent DNS leak.

        Why this test exists: setting ipv4.dns to a public resolver was the
        rejected design — NetworkManager orders it ahead of the DHCP-supplied
        server, so it silently becomes the primary for every lookup rather than
        a fallback. Recommending it in the banner reintroduces by habit exactly
        what was rejected by design.

        How the regression manifests: a public resolver address appears in the
        login banner as a suggested fix.
        """
        out = run_check(resolves=False, resolv_conf=WORKING_RESOLV)

        for resolver in PUBLIC_RESOLVERS:
            assert resolver not in out

    def test_stays_silent_when_no_nameserver_is_configured(self, run_check):
        """No nameserver means nothing to blame. This is the empty case.

        Why this test exists: with an empty resolv.conf the lookup also fails,
        but the cause is local configuration rather than a dead host. Printing
        the host-forwarder explanation would be actively misleading.

        How the regression manifests: the warning appears naming an empty
        server, e.g. "uses  as its DNS server".
        """
        assert run_check(resolves=False, resolv_conf="# nothing here\n") == ""

    def test_stays_silent_when_there_is_no_default_route(self, run_check):
        """A down link is a different fault and must not be reported as DNS.

        Why this test exists: with no host sharing the Pi has no route at all,
        and lookups fail for that reason. Blaming DNS sends the user to restart
        a forwarder when the actual fix is enabling Internet Sharing.

        How the regression manifests: the DNS warning appears on a board with
        no default route.
        """
        assert run_check(resolves=False, resolv_conf=WORKING_RESOLV, default_route="") == ""

    def test_stays_silent_when_timeout_is_unavailable_and_dns_works(self, run_check):
        """A missing `timeout` must not be mistaken for a DNS failure.

        Why this test exists: the first implementation ran the probe as
        `timeout 2 getent ...` unconditionally. Where `timeout` does not exist
        the command fails with 127, which is indistinguishable from a failed
        lookup, so the script printed the DNS warning on every single login of
        a perfectly healthy board. This was caught on macOS, which ships no
        coreutils `timeout`.

        How the regression manifests: output on a resolving board that has no
        `timeout` binary.
        """
        assert run_check(resolves=True, resolv_conf=WORKING_RESOLV, with_timeout=False) == ""

    def test_still_warns_without_timeout_when_dns_is_broken(self, run_check):
        """The fallback path must keep working, not just stay quiet.

        Why this test exists: the cheapest way to satisfy the test above is to
        exit early whenever `timeout` is missing, which would silently disable
        the diagnostic on those systems. This pins the failure case.

        How the regression manifests: no warning on a broken board that has no
        `timeout` binary.
        """
        out = run_check(resolves=False, resolv_conf=WORKING_RESOLV, with_timeout=False)
        assert HOST_NAMESERVER in out

    def test_is_valid_posix_shell(self):
        """The script must parse under plain sh, not just bash.

        Why this test exists: it runs from /etc/update-motd.d via pam_motd with
        a #!/bin/sh shebang, which is dash on Debian. A bashism would fail at
        login on the board while working fine on a developer's machine.

        How the regression manifests: a syntax error from dash.
        """
        shell = shutil.which("dash") or "/bin/sh"
        proc = subprocess.run(  # noqa: S603 - syntax check only
            [shell, "-n", str(SCRIPT)],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        assert proc.returncode == 0, proc.stderr

    def test_is_executable(self):
        """The file must ship with the executable bit.

        Why this test exists: pam_motd silently skips non-executable files in
        update-motd.d, so a missing mode bit disables the diagnostic with no
        error anywhere.

        How the regression manifests: the mode loses its execute bits.
        """
        assert SCRIPT.stat().st_mode & 0o111
