"""Turning an installed engine binary into a usable engine, and reporting it.

Installing a binary is only half of making an engine playable: the writable
``.uci`` profile config -- the strength ladder the Elo picker and the profile
editor read -- is generated by launching the engine once and recording the UCI
options it advertises. That second step was performed at two call sites
(``EngineManager.install_engine`` for catalog engines, the web app's custom
upload/URL path for the rest), each with its own copy of a try/except that
logged the failure and continued. An engine could therefore finish installing,
fail to initialize, and present itself as "Installed" with no profiles and no
explanation the user could reach.

This module is the single implementation of that step. Beyond removing the
duplication it does the two things neither copy did: it records the reason
durably (:mod:`engine_failure_record`) so the engines list can report it, and it
appends an error to the system event log (:mod:`event_log`) so the failure has a
timestamped trail that survives the user dismissing the notice.

Neither entry point raises. The binary is already installed by the time these
run, so a failed probe must not turn a completed install into a reported
failure -- that would offer the user a reinstall that cannot help.
"""

from typing import Optional

from universalchess.board.logging import log
from universalchess.services import uci_schema
from universalchess.services.engine_failure_record import (
    PHASE_INITIALIZE,
    STORE,
    EngineFailureStore,
)
from universalchess.services.engine_registry import LOAD_FAILURE_UNKNOWN
from universalchess.services.event_log import log_event

# Event-log category for engine initialization, distinct from ``engine_install``
# so the viewer can tell "the install failed" from "the install worked and the
# engine will not start" -- different problems with different repairs.
EVENT_CATEGORY = "engine_init"


def initialize_profiles(
    engine_name: str,
    *,
    config_path: Optional[str] = None,
    display_name: Optional[str] = None,
    store: Optional[EngineFailureStore] = None,
) -> bool:
    """Seed ``engine_name``'s profile config if absent, recording the outcome.

    Create-if-absent, matching :func:`uci_schema.seed_config`: an existing config
    is left untouched so user edits survive a reinstall.

    Args:
        engine_name: Catalog or custom engine id.
        config_path: Explicit ``.uci`` location; the custom upload/URL install
            path resolves this itself. Defaults to the standard location.
        display_name: Human-readable name for the event-log entry. Falls back to
            ``engine_name``; the engine catalog is not imported here because it
            already depends on this layer.
        store: Failure store to record into (injected by tests).

    Returns:
        True if the engine now has a profile config.
    """
    return _seed_recording_outcome(
        engine_name,
        seed=lambda: uci_schema.seed_config(engine_name, config_path=config_path),
        display_name=display_name,
        store=store,
    )


def reset_profiles(
    engine_name: str,
    *,
    config_path: Optional[str] = None,
    display_name: Optional[str] = None,
    store: Optional[EngineFailureStore] = None,
) -> str:
    """Discard ``engine_name``'s profile config and seed a fresh one, recording it.

    The operator escape hatch behind "Reset profiles", wrapped in the same
    reporting as the post-install seed: a reset is an initialization attempt, and
    it is the one the user makes deliberately after noticing something wrong, so
    its outcome must reach the same places.

    Unlike :func:`initialize_profiles` this propagates
    :class:`uci_schema.EngineProbeError` -- the caller is an endpoint answering a
    user action, and the user is waiting to be told whether it worked.

    Returns:
        The config path that was seeded.
    """
    failures = store if store is not None else STORE
    try:
        path = uci_schema.reset_config(engine_name, config_path=config_path)
    except uci_schema.EngineProbeError as probe_error:
        _record(failures, engine_name, display_name, probe_error)
        raise
    failures.clear(engine_name)
    return path


def _seed_recording_outcome(engine_name, *, seed, display_name, store) -> bool:
    """Run ``seed``, clearing or recording the engine's failure record."""
    failures = store if store is not None else STORE
    try:
        seed()
    except uci_schema.EngineProbeError as probe_error:
        _record(failures, engine_name, display_name, probe_error)
        return False
    except Exception as unexpected:  # noqa: BLE001 - must not fail a good install
        log.warning(
            "[engine_bootstrap] Unexpected error initializing '%s': %s",
            engine_name, unexpected,
        )
        _record(failures, engine_name, display_name, unexpected)
        return False
    failures.clear(engine_name)
    return True


def _record(failures, engine_name, display_name, error) -> None:
    """Persist the failure and append the matching system event-log entry.

    Persisting is best-effort. The record exists to report a problem, so it must
    never be able to create one: an unwritable config dir would otherwise turn a
    completed install into a reported failure, which is both untrue and the
    opposite of what this code is for. The event log and the application log
    still carry the reason when the store cannot be written.
    """
    label = display_name or engine_name
    reason_code = getattr(error, "reason_code", None) or LOAD_FAILURE_UNKNOWN
    detail = getattr(error, "detail", None)

    try:
        failures.record_failure(
            engine_name,
            phase=PHASE_INITIALIZE,
            reason_code=reason_code,
            detail=detail,
        )
    except OSError as store_error:
        log.warning(
            "[engine_bootstrap] Could not persist failure for '%s': %s",
            engine_name, store_error,
        )
    detail_suffix = f"; {detail}" if detail else ""
    log_event(
        EVENT_CATEGORY,
        f"{label} did not start after install ({reason_code}{detail_suffix})",
        level="error",
    )
    log.error(
        "[engine_bootstrap] '%s' installed but failed to initialize: %s (%s)",
        engine_name, reason_code, error,
    )


__all__ = [
    "EVENT_CATEGORY",
    "initialize_profiles",
    "reset_profiles",
]
